/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import calculadorabases.*;
import java.awt.Color;
/**
 *
 * @author Ricardo Alberto Hernandez Aguila
 */
public class CalculadoraBasesGUI extends javax.swing.JFrame {
    
    private Calculadora calculadora;
    private Operacion operacion; 
    private boolean estado;
    private int base;
    /**
     * Creates new form CalculadoraBasesGUI
     */
    public CalculadoraBasesGUI() {
        initComponents();
        calculadora = new Calculadora();
        operacion = calculadora.getCalculadoraBase(2);
        estado = false;
        base = 2;
        jTextFieldDisplay.setFocusable(false);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonMultiplication = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jComboBoxBases = new javax.swing.JComboBox<>();
        jButtonAns = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 4, 15, 10));

        jButtonD.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonD.setText("D");
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonD);

        jButtonE.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonE.setText("E");
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonE);

        jButtonF.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonF.setText("F");
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonF);

        jButtonDel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonDel.setText("<<");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDel);

        jButtonA.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonA);

        jButtonB.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonB.setText("B");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonB);

        jButtonC.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButtonC);

        jButtonMultiplication.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonMultiplication.setText("*");
        jButtonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedOperador(evt);
            }
        });
        jPanel1.add(jButtonMultiplication);

        jButton7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButtonMinus.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedOperador(evt);
            }
        });
        jPanel1.add(jButtonMinus);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButtonPlus.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedOperador(evt);
            }
        });
        jPanel1.add(jButtonPlus);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButtonEquals.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEquals);

        jButton0.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraBasesGUI.this.actionPerformed(evt);
            }
        });
        jPanel1.add(jButton0);

        jComboBoxBases.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxBases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base 2", "Base 3", "Base 4", "Base 5", "Base 6", "Base 7", "Base 8", "Base 9", "Base 10", "Base 16" }));
        jComboBoxBases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBasesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBases);

        jButtonAns.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonAns.setText("ANS");
        jButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAns);

        jButtonClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonClear.setText("CE");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear);

        jTextFieldDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        // TODO add your handling code here:
        if(jTextFieldDisplay.getText().equals("0")){
            jTextFieldDisplay.setText("");
        }
        javax.swing.JButton jb = (javax.swing.JButton)evt.getSource();
        jTextFieldDisplay.setText(jTextFieldDisplay.getText()+jb.getText());
    }//GEN-LAST:event_actionPerformed

    private void actionPerformedOperador(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformedOperador
        // TODO add your handling code here:
        javax.swing.JButton jb = (javax.swing.JButton)evt.getSource();
        String cadena = jTextFieldDisplay.getText();
        int posicion =0;
        if(cadena.indexOf('+') != -1){
            posicion = cadena.indexOf('+')+1;
        }
        if(cadena.substring(1).indexOf('-') != -1){
            posicion = cadena.indexOf('-')+1;
        }
        if(cadena.indexOf('*') != -1){
            posicion = cadena.indexOf('*')+1;
        }
        if(!estado&&base<=10){
            estado = true;
            operacion.setOperando1(Integer.parseInt(cadena));
            jTextFieldDisplay.setText(cadena+jb.getText());
            operacion.setOperador(jb.getText().charAt(0));
        }else if(estado&&base<=10){            
            operacion.setOperando2(Integer.parseInt(cadena.substring(posicion)));
            operacion.realizarOperacion();
            jTextFieldDisplay.setText(String.valueOf(operacion.getResultado())+jb.getText());
            operacion.setOperando1(operacion.getResultado());
            operacion.setOperador(jb.getText().charAt(0));
        }else if(!estado&&base>10){
            estado = true;
            operacion.setOperando1(cadena);
            jTextFieldDisplay.setText(cadena+jb.getText());
            operacion.setOperador(jb.getText().charAt(0));
        }else if(estado&&base>10){
            operacion.setOperando2(cadena.substring(posicion));
            operacion.realizarOperacion();
            jTextFieldDisplay.setText(operacion.getResultado()+jb.getText());
            operacion.setOperando1(operacion.getResultado());
            operacion.setOperador(jb.getText().charAt(0));
        }        
    }//GEN-LAST:event_actionPerformedOperador

    private void jComboBoxBasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBasesActionPerformed
        // TODO add your handling code here:
        estado=false;
        jTextFieldDisplay.setText("0");
        String basebox = jComboBoxBases.getSelectedItem().toString();
        base = Integer.parseInt(basebox.substring(5));
        operacion = calculadora.getCalculadoraBase(base);
        System.out.println("Base "+ base);
    }//GEN-LAST:event_jComboBoxBasesActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        estado = false;
        jTextFieldDisplay.setText("0");        
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnsActionPerformed
        // TODO add your handling code here:
        if(!estado){
            jTextFieldDisplay.setText(String.valueOf(operacion.getResultado()));
        }else{
            jTextFieldDisplay.setText(jTextFieldDisplay.getText()+operacion.getResultado());
        }
    }//GEN-LAST:event_jButtonAnsActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here: 
        char last =jTextFieldDisplay.getText().charAt(jTextFieldDisplay.getText().length()-1);
        if(last=='+'||last=='-'||last=='*'){
            estado = false;            
        }
        jTextFieldDisplay.setText(jTextFieldDisplay.getText().substring(0, jTextFieldDisplay.getText().length()-1));
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        // TODO add your handling code here:
        char last =jTextFieldDisplay.getText().charAt(jTextFieldDisplay.getText().length()-1);
        String cadena = jTextFieldDisplay.getText();
        int posicion =0;
        if(cadena.indexOf('+') != -1){
            posicion = cadena.indexOf('+')+1;
        }
        if(cadena.substring(1).indexOf('-') != -1){
            posicion = cadena.indexOf('-')+1;
        }
        if(cadena.indexOf('*') != -1){
            posicion = cadena.indexOf('*')+1;
        }
        if(last!='+'&&last!='-'&&last!='*'){
            if(base<=10){
                operacion.setOperando2(Integer.parseInt(cadena.substring(posicion)));
            }else if(base>10){
                operacion.setOperando2(cadena.substring(posicion));
            }
            operacion.realizarOperacion();
            operacion.setOperando1(operacion.getResultado());
            jTextFieldDisplay.setText(String.valueOf(operacion.getResultado()));
            estado = false;            
        }
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBasesGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonAns;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiplication;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JComboBox<String> jComboBoxBases;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
